device:
  name: MyDavisWeatherStation
  hostname: 10.50.0.104
  port: 22222
storage:
    grpc:
        use-tls: false
        port: 7500
    influxdb:
        scheme: http
        host:  10.50.0.35
        port: 8086
        protocol: http
        database: weather
        username: weather
        password: someSecretPassword
