devices:
  - name: DavisVantagePro2
    type: davis
    hostname: 192.168.0.20
    port: 22222
  - name: CSI
    type: campbellscientific
    serialdevice: /dev/ttyACM0
controllers:
  - type: pwsweather
    pwsweather:
      station-id: MYSTATION
      api-key: your-api-key-goes-here
      upload-interval: 60
      pull-from-device: CSI
  - type: weatherunderground
    weatherunderground:
      station-id: MYSTATION
      api-key: your-api-key-goes-here
      upload-interval: 60
      pull-from-device: DavisVantagePro2
storage:
    grpc:
        cert: /tls/live/mysite.com/fullchain.pem
        key: /tls/live/mysite.com/privkey.pem
        port: 7500
    rest:
        cert: /tls/live/mysite.com/fullchain.pem
        key: /tls/live/mysite.com/privkey.pem
        listen-addr: 0.0.0.0
        port: 7501
        weather-site:
          station-name: My Weather Station
          pull-from-device: CSI
          page-title: Hometown Weather
          about-station-html: |
            <h2>About This Station</h2>
            <p>
            This is my weather station.  There are many like it, but this one is mine.
    timescaledb:
        connection-string: host=localhost port=5432 dbname=weather user=weather password=PASSWORD TimeZone=US/Mountain
        timezone: US/Mountain
    aprs:
        callsign: YOURCALL
        passcode: 1234
        aprs-is-server: rotate.aprs2.net:14580
        location:
            latitude: 40.475819
            longitude: -111.845340