version: '2'
services:
  gopherwx:
    network_mode: "host"
    image: chrissnell/gopherwx
    environment:
    - GOPHERWX_CONFIG=/config/config.yaml
    volumes:
     - /etc/gopherwx:/config
     - /etc/letsencrypt:/tls
