version: '2'
services:
  remoteweather:
    network_mode: "host"
    image: chrissnell/remoteweather:v4.0
    environment:
    - REMOTEWEATHER_CONFIG=/config/config.yaml
    volumes:
     - /etc/remoteweather:/config
     - /etc/letsencrypt:/tls
