project_name: remoteweather

# Skip the build phase - we're using pre-built binaries from GitHub Actions
builds:
  - skip: true

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip

nfpms:
  - id: packages
    package_name: remoteweather
    vendor: Chris Snell
    homepage: https://github.com/chrissnell/remoteweather
    maintainer: Chris Snell
    description: Weather station data collection and distribution system
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: packaging/systemd/remoteweather.service
        dst: /usr/lib/systemd/system/remoteweather.service
        type: config
    scripts:
      postinstall: packaging/deb/postinst
      preremove: packaging/deb/prerm
    overrides:
      rpm:
        file_name_template: '{{ .ProjectName }}-{{ .Version }}-1.{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else if eq .Arch "arm" }}armhf{{ else }}{{ .Arch }}{{ end }}'
        contents:
          - src: packaging/systemd/remoteweather.service
            dst: /usr/lib/systemd/system/remoteweather.service
            type: config
        scripts:
          preinstall: packaging/rpm/preinstall.sh
          postinstall: packaging/rpm/postinstall.sh
          preremove: packaging/rpm/preremove.sh
      deb:
        file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Arch "arm" }}armhf{{ else }}{{ .Arch }}{{ end }}'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

dockers:
  - image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-amd64"
      - "ghcr.io/chrissnell/remoteweather:latest-amd64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/chrissnell/remoteweather"
    goarch: amd64
    goos: linux
    dockerfile: Dockerfile
    
  - image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-arm64"
      - "ghcr.io/chrissnell/remoteweather:latest-arm64"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/chrissnell/remoteweather"
    goarch: arm64
    goos: linux
    dockerfile: Dockerfile
    
  - image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-armv7"
      - "ghcr.io/chrissnell/remoteweather:latest-armv7"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/chrissnell/remoteweather"
    goarch: arm
    goarm: "7"
    goos: linux
    dockerfile: Dockerfile
    
  - image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-armv6"
      - "ghcr.io/chrissnell/remoteweather:latest-armv6"
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/chrissnell/remoteweather"
    goarch: arm
    goarm: "6"
    goos: linux
    dockerfile: Dockerfile

docker_manifests:
  - name_template: "ghcr.io/chrissnell/remoteweather:{{ .Version }}"
    image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-amd64"
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-arm64"
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-armv7"
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-armv6"
      
  - name_template: "ghcr.io/chrissnell/remoteweather:latest"
    image_templates:
      - "ghcr.io/chrissnell/remoteweather:latest-amd64"
      - "ghcr.io/chrissnell/remoteweather:latest-arm64"
      - "ghcr.io/chrissnell/remoteweather:latest-armv7"
      - "ghcr.io/chrissnell/remoteweather:latest-armv6"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'