project_name: remoteweather

before:
  hooks:
    - go mod tidy

builds:
  # Migrate tool - Linux AMD64
  - id: migrate-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/migrate
    ldflags:
      - -s -w
    binary: remoteweather-migrate

  # Migrate tool - Linux ARM64
  - id: migrate-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/migrate
    ldflags:
      - -s -w
    binary: remoteweather-migrate

  # Migrate tool - Linux ARMv7
  - id: migrate-armv7
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    main: ./cmd/migrate
    ldflags:
      - -s -w
    binary: remoteweather-migrate

  # Migrate tool - Linux ARMv6
  - id: migrate-armv6
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "6"
    main: ./cmd/migrate
    ldflags:
      - -s -w
    binary: remoteweather-migrate

  # TimescaleDB Provisioner - Linux AMD64
  - id: timescaledb-provisioner-amd64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/remoteweather-timescaledb-provisioner
    ldflags:
      - -s -w
    binary: remoteweather-timescaledb-provisioner

  # TimescaleDB Provisioner - Linux ARM64
  - id: timescaledb-provisioner-arm64
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/remoteweather-timescaledb-provisioner
    ldflags:
      - -s -w
    binary: remoteweather-timescaledb-provisioner

  # TimescaleDB Provisioner - Linux ARMv7
  - id: timescaledb-provisioner-armv7
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    main: ./cmd/remoteweather-timescaledb-provisioner
    ldflags:
      - -s -w
    binary: remoteweather-timescaledb-provisioner

  # TimescaleDB Provisioner - Linux ARMv6
  - id: timescaledb-provisioner-armv6
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "6"
    main: ./cmd/remoteweather-timescaledb-provisioner
    ldflags:
      - -s -w
    binary: remoteweather-timescaledb-provisioner

  # Windows builds (no CGO needed for serial on Windows)
  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    main: ./cmd/remoteweather
    ldflags:
      - -s -w -X github.com/chrissnell/remoteweather/internal/constants.Version={{.Version}} -X github.com/chrissnell/remoteweather/internal/constants.CommitID={{.FullCommit}}
    binary: remoteweather

  # Linux AMD64 with CGO
  - id: linux-amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/remoteweather
    ldflags:
      - -s -w -X github.com/chrissnell/remoteweather/internal/constants.Version={{.Version}} -X github.com/chrissnell/remoteweather/internal/constants.CommitID={{.FullCommit}}
    binary: remoteweather

  # Linux ARM64 with CGO (Raspberry Pi 3/4/5 64-bit)
  - id: linux-arm64
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    goos:
      - linux
    goarch:
      - arm64
    main: ./cmd/remoteweather
    ldflags:
      - -s -w -X github.com/chrissnell/remoteweather/internal/constants.Version={{.Version}} -X github.com/chrissnell/remoteweather/internal/constants.CommitID={{.FullCommit}}
    binary: remoteweather

  # Linux ARMv7 with CGO (Raspberry Pi 2/3/4 32-bit)
  - id: linux-armv7
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabihf-gcc
      - CXX=arm-linux-gnueabihf-g++
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "7"
    main: ./cmd/remoteweather
    ldflags:
      - -s -w -X github.com/chrissnell/remoteweather/internal/constants.Version={{.Version}} -X github.com/chrissnell/remoteweather/internal/constants.CommitID={{.FullCommit}}
    binary: remoteweather

  # Linux ARMv6 with CGO (Raspberry Pi Zero/1)
  - id: linux-armv6
    env:
      - CGO_ENABLED=1
      - CC=arm-linux-gnueabi-gcc
      - CXX=arm-linux-gnueabi-g++
    goos:
      - linux
    goarch:
      - arm
    goarm:
      - "6"
    main: ./cmd/remoteweather
    ldflags:
      - -s -w -X github.com/chrissnell/remoteweather/internal/constants.Version={{.Version}} -X github.com/chrissnell/remoteweather/internal/constants.CommitID={{.FullCommit}}
    binary: remoteweather


archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    builds:
      - windows
      - linux-amd64
      - linux-arm64
      - linux-armv7
      - linux-armv6
    files:
      - none*  # Only include the binary

nfpms:
  - id: packages
    package_name: remoteweather
    vendor: Chris Snell
    homepage: https://github.com/chrissnell/remoteweather
    maintainer: Chris Snell
    description: Weather station data collection and distribution system
    license: MIT
    formats:
      - deb
      - rpm
    builds:
      - linux-amd64
      - linux-arm64
      - linux-armv7
      - linux-armv6
      - migrate-amd64
      - migrate-arm64
      - migrate-armv7
      - migrate-armv6
      - timescaledb-provisioner-amd64
      - timescaledb-provisioner-arm64
      - timescaledb-provisioner-armv7
      - timescaledb-provisioner-armv6
    bindir: /usr/bin
    contents:
      - src: packaging/systemd/remoteweather.service
        dst: /usr/lib/systemd/system/remoteweather.service
        type: config
      - src: migrations/config/*.sql
        dst: /usr/share/remoteweather/migrations/config/
      - src: migrations/weather/*.sql
        dst: /usr/share/remoteweather/migrations/weather/
    scripts:
      postinstall: packaging/deb/postinst
      preremove: packaging/deb/prerm
    overrides:
      rpm:
        file_name_template: '{{ .ProjectName }}-{{ .Version }}-1.{{ if eq .Arch "amd64" }}x86_64{{ else if eq .Arch "arm64" }}aarch64{{ else if eq .Arch "arm" }}{{ if eq .Arm "6" }}armv6{{ else if eq .Arm "7" }}armv7{{ else }}armhf{{ end }}{{ else }}{{ .Arch }}{{ end }}'
        contents:
          - src: packaging/systemd/remoteweather.service
            dst: /usr/lib/systemd/system/remoteweather.service
            type: config
          - src: migrations/config/*.sql
            dst: /usr/share/remoteweather/migrations/config/
          - src: migrations/weather/*.sql
            dst: /usr/share/remoteweather/migrations/weather/
        scripts:
          preinstall: packaging/rpm/preinstall.sh
          postinstall: packaging/rpm/postinstall.sh
          preremove: packaging/rpm/preremove.sh
      deb:
        file_name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Arch "arm" }}{{ if eq .Arm "6" }}armv6{{ else if eq .Arm "7" }}armv7{{ else }}armhf{{ end }}{{ else }}{{ .Arch }}{{ end }}'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

dockers:
  - image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-amd64"
      - "ghcr.io/chrissnell/remoteweather:latest-amd64"
    ids:
      - linux-amd64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/chrissnell/remoteweather"
    goarch: amd64
    goos: linux
    dockerfile: Dockerfile
    
  - image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-arm64"
      - "ghcr.io/chrissnell/remoteweather:latest-arm64"
    ids:
      - linux-arm64
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/chrissnell/remoteweather"
    goarch: arm64
    goos: linux
    dockerfile: Dockerfile
    
  - image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-armv7"
      - "ghcr.io/chrissnell/remoteweather:latest-armv7"
    ids:
      - linux-armv7
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v7"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/chrissnell/remoteweather"
    goarch: arm
    goarm: "7"
    goos: linux
    dockerfile: Dockerfile
    
  - image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-armv6"
      - "ghcr.io/chrissnell/remoteweather:latest-armv6"
    ids:
      - linux-armv6
    use: buildx
    build_flag_templates:
      - "--pull"
      - "--platform=linux/arm/v6"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source=https://github.com/chrissnell/remoteweather"
    goarch: arm
    goarm: "6"
    goos: linux
    dockerfile: Dockerfile

docker_manifests:
  - name_template: "ghcr.io/chrissnell/remoteweather:{{ .Version }}"
    image_templates:
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-amd64"
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-arm64"
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-armv7"
      - "ghcr.io/chrissnell/remoteweather:{{ .Version }}-armv6"
      
  - name_template: "ghcr.io/chrissnell/remoteweather:latest"
    image_templates:
      - "ghcr.io/chrissnell/remoteweather:latest-amd64"
      - "ghcr.io/chrissnell/remoteweather:latest-arm64"
      - "ghcr.io/chrissnell/remoteweather:latest-armv7"
      - "ghcr.io/chrissnell/remoteweather:latest-armv6"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

release:
  replace_existing_artifacts: true
  mode: replace
  draft: false
  prerelease: auto