// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v5.27.1
// source: protocols/weatherapps/weatherapps.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	WeatherAppsV1_StreamLiveWeather_FullMethodName  = "/WeatherAppsV1/StreamLiveWeather"
	WeatherAppsV1_GetWeatherTimeSpan_FullMethodName = "/WeatherAppsV1/GetWeatherTimeSpan"
	WeatherAppsV1_GetCurrentReading_FullMethodName  = "/WeatherAppsV1/GetCurrentReading"
)

// WeatherAppsV1Client is the client API for WeatherAppsV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WeatherApps service v1.0 - end-user weather data streaming API
// This protocol is designed for consumption by weather applications and provides
// calculated, user-friendly values (rain totals, feels-like temp, etc.) sourced
// from the same data that feeds the /latest REST endpoint.
type WeatherAppsV1Client interface {
	// Get live streaming weather readings for display in apps
	StreamLiveWeather(ctx context.Context, in *LiveWeatherRequest, opts ...grpc.CallOption) (WeatherAppsV1_StreamLiveWeatherClient, error)
	// Get weather data over a time span
	GetWeatherTimeSpan(ctx context.Context, in *WeatherSpanRequest, opts ...grpc.CallOption) (*WeatherSpan, error)
	// Get the latest reading for a station
	GetCurrentReading(ctx context.Context, in *LatestReadingRequest, opts ...grpc.CallOption) (*WeatherReading, error)
}

type weatherAppsV1Client struct {
	cc grpc.ClientConnInterface
}

func NewWeatherAppsV1Client(cc grpc.ClientConnInterface) WeatherAppsV1Client {
	return &weatherAppsV1Client{cc}
}

func (c *weatherAppsV1Client) StreamLiveWeather(ctx context.Context, in *LiveWeatherRequest, opts ...grpc.CallOption) (WeatherAppsV1_StreamLiveWeatherClient, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WeatherAppsV1_ServiceDesc.Streams[0], WeatherAppsV1_StreamLiveWeather_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &weatherAppsV1StreamLiveWeatherClient{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type WeatherAppsV1_StreamLiveWeatherClient interface {
	Recv() (*WeatherReading, error)
	grpc.ClientStream
}

type weatherAppsV1StreamLiveWeatherClient struct {
	grpc.ClientStream
}

func (x *weatherAppsV1StreamLiveWeatherClient) Recv() (*WeatherReading, error) {
	m := new(WeatherReading)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *weatherAppsV1Client) GetWeatherTimeSpan(ctx context.Context, in *WeatherSpanRequest, opts ...grpc.CallOption) (*WeatherSpan, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeatherSpan)
	err := c.cc.Invoke(ctx, WeatherAppsV1_GetWeatherTimeSpan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *weatherAppsV1Client) GetCurrentReading(ctx context.Context, in *LatestReadingRequest, opts ...grpc.CallOption) (*WeatherReading, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeatherReading)
	err := c.cc.Invoke(ctx, WeatherAppsV1_GetCurrentReading_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WeatherAppsV1Server is the server API for WeatherAppsV1 service.
// All implementations must embed UnimplementedWeatherAppsV1Server
// for forward compatibility
//
// WeatherApps service v1.0 - end-user weather data streaming API
// This protocol is designed for consumption by weather applications and provides
// calculated, user-friendly values (rain totals, feels-like temp, etc.) sourced
// from the same data that feeds the /latest REST endpoint.
type WeatherAppsV1Server interface {
	// Get live streaming weather readings for display in apps
	StreamLiveWeather(*LiveWeatherRequest, WeatherAppsV1_StreamLiveWeatherServer) error
	// Get weather data over a time span
	GetWeatherTimeSpan(context.Context, *WeatherSpanRequest) (*WeatherSpan, error)
	// Get the latest reading for a station
	GetCurrentReading(context.Context, *LatestReadingRequest) (*WeatherReading, error)
	mustEmbedUnimplementedWeatherAppsV1Server()
}

// UnimplementedWeatherAppsV1Server must be embedded to have forward compatible implementations.
type UnimplementedWeatherAppsV1Server struct {
}

func (UnimplementedWeatherAppsV1Server) StreamLiveWeather(*LiveWeatherRequest, WeatherAppsV1_StreamLiveWeatherServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamLiveWeather not implemented")
}
func (UnimplementedWeatherAppsV1Server) GetWeatherTimeSpan(context.Context, *WeatherSpanRequest) (*WeatherSpan, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWeatherTimeSpan not implemented")
}
func (UnimplementedWeatherAppsV1Server) GetCurrentReading(context.Context, *LatestReadingRequest) (*WeatherReading, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrentReading not implemented")
}
func (UnimplementedWeatherAppsV1Server) mustEmbedUnimplementedWeatherAppsV1Server() {}

// UnsafeWeatherAppsV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WeatherAppsV1Server will
// result in compilation errors.
type UnsafeWeatherAppsV1Server interface {
	mustEmbedUnimplementedWeatherAppsV1Server()
}

func RegisterWeatherAppsV1Server(s grpc.ServiceRegistrar, srv WeatherAppsV1Server) {
	s.RegisterService(&WeatherAppsV1_ServiceDesc, srv)
}

func _WeatherAppsV1_StreamLiveWeather_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LiveWeatherRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(WeatherAppsV1Server).StreamLiveWeather(m, &weatherAppsV1StreamLiveWeatherServer{ServerStream: stream})
}

type WeatherAppsV1_StreamLiveWeatherServer interface {
	Send(*WeatherReading) error
	grpc.ServerStream
}

type weatherAppsV1StreamLiveWeatherServer struct {
	grpc.ServerStream
}

func (x *weatherAppsV1StreamLiveWeatherServer) Send(m *WeatherReading) error {
	return x.ServerStream.SendMsg(m)
}

func _WeatherAppsV1_GetWeatherTimeSpan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeatherSpanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherAppsV1Server).GetWeatherTimeSpan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherAppsV1_GetWeatherTimeSpan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherAppsV1Server).GetWeatherTimeSpan(ctx, req.(*WeatherSpanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WeatherAppsV1_GetCurrentReading_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatestReadingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WeatherAppsV1Server).GetCurrentReading(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WeatherAppsV1_GetCurrentReading_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WeatherAppsV1Server).GetCurrentReading(ctx, req.(*LatestReadingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WeatherAppsV1_ServiceDesc is the grpc.ServiceDesc for WeatherAppsV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WeatherAppsV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "WeatherAppsV1",
	HandlerType: (*WeatherAppsV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWeatherTimeSpan",
			Handler:    _WeatherAppsV1_GetWeatherTimeSpan_Handler,
		},
		{
			MethodName: "GetCurrentReading",
			Handler:    _WeatherAppsV1_GetCurrentReading_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamLiveWeather",
			Handler:       _WeatherAppsV1_StreamLiveWeather_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protocols/weatherapps/weatherapps.proto",
}
