// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.1
// source: protocols/snowgauge/snowgauge.proto

package snowgauge

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Define the request message
type StreamRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationName *string `protobuf:"bytes,1,opt,name=stationName,proto3,oneof" json:"stationName,omitempty"`
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_snowgauge_snowgauge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_snowgauge_snowgauge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_protocols_snowgauge_snowgauge_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetStationName() string {
	if x != nil && x.StationName != nil {
		return *x.StationName
	}
	return ""
}

// Define the response message
type Reading struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StationName       string               `protobuf:"bytes,1,opt,name=stationName,proto3" json:"stationName,omitempty"`             // Name of snow gauge
	Distance          int32                `protobuf:"varint,2,opt,name=distance,proto3" json:"distance,omitempty"`                  // Reading value in mm
	SystemUptime      *durationpb.Duration `protobuf:"bytes,3,opt,name=systemUptime,proto3" json:"systemUptime,omitempty"`           // Uptime of snow gauge
	ApplicationUptime *durationpb.Duration `protobuf:"bytes,4,opt,name=applicationUptime,proto3" json:"applicationUptime,omitempty"` // Uptime of application
}

func (x *Reading) Reset() {
	*x = Reading{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocols_snowgauge_snowgauge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reading) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reading) ProtoMessage() {}

func (x *Reading) ProtoReflect() protoreflect.Message {
	mi := &file_protocols_snowgauge_snowgauge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reading.ProtoReflect.Descriptor instead.
func (*Reading) Descriptor() ([]byte, []int) {
	return file_protocols_snowgauge_snowgauge_proto_rawDescGZIP(), []int{1}
}

func (x *Reading) GetStationName() string {
	if x != nil {
		return x.StationName
	}
	return ""
}

func (x *Reading) GetDistance() int32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *Reading) GetSystemUptime() *durationpb.Duration {
	if x != nil {
		return x.SystemUptime
	}
	return nil
}

func (x *Reading) GetApplicationUptime() *durationpb.Duration {
	if x != nil {
		return x.ApplicationUptime
	}
	return nil
}

var File_protocols_snowgauge_snowgauge_proto protoreflect.FileDescriptor

var file_protocols_snowgauge_snowgauge_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x2f, 0x73, 0x6e, 0x6f, 0x77,
	0x67, 0x61, 0x75, 0x67, 0x65, 0x2f, 0x73, 0x6e, 0x6f, 0x77, 0x67, 0x61, 0x75, 0x67, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x6e, 0x6f, 0x77, 0x67, 0x61, 0x75, 0x67, 0x65,
	0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x46, 0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x25, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0xcf, 0x01, 0x0a, 0x07, 0x52, 0x65, 0x61,
	0x64, 0x69, 0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x64, 0x69, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x52, 0x0c, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x55, 0x70, 0x74, 0x69, 0x6d,
	0x65, 0x12, 0x47, 0x0a, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x44,
	0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x11, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x55, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x32, 0x53, 0x0a, 0x10, 0x53, 0x6e,
	0x6f, 0x77, 0x47, 0x61, 0x75, 0x67, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f,
	0x0a, 0x0d, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x12,
	0x18, 0x2e, 0x73, 0x6e, 0x6f, 0x77, 0x67, 0x61, 0x75, 0x67, 0x65, 0x2e, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x73, 0x6e, 0x6f, 0x77,
	0x67, 0x61, 0x75, 0x67, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x69, 0x6e, 0x67, 0x30, 0x01, 0x42,
	0x39, 0x5a, 0x37, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68,
	0x72, 0x69, 0x73, 0x73, 0x6e, 0x65, 0x6c, 0x6c, 0x2f, 0x72, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x77,
	0x65, 0x61, 0x74, 0x68, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73,
	0x2f, 0x73, 0x6e, 0x6f, 0x77, 0x67, 0x61, 0x75, 0x67, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protocols_snowgauge_snowgauge_proto_rawDescOnce sync.Once
	file_protocols_snowgauge_snowgauge_proto_rawDescData = file_protocols_snowgauge_snowgauge_proto_rawDesc
)

func file_protocols_snowgauge_snowgauge_proto_rawDescGZIP() []byte {
	file_protocols_snowgauge_snowgauge_proto_rawDescOnce.Do(func() {
		file_protocols_snowgauge_snowgauge_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocols_snowgauge_snowgauge_proto_rawDescData)
	})
	return file_protocols_snowgauge_snowgauge_proto_rawDescData
}

var file_protocols_snowgauge_snowgauge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocols_snowgauge_snowgauge_proto_goTypes = []any{
	(*StreamRequest)(nil),       // 0: snowgauge.StreamRequest
	(*Reading)(nil),             // 1: snowgauge.Reading
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_protocols_snowgauge_snowgauge_proto_depIdxs = []int32{
	2, // 0: snowgauge.Reading.systemUptime:type_name -> google.protobuf.Duration
	2, // 1: snowgauge.Reading.applicationUptime:type_name -> google.protobuf.Duration
	0, // 2: snowgauge.SnowGaugeService.StreamReading:input_type -> snowgauge.StreamRequest
	1, // 3: snowgauge.SnowGaugeService.StreamReading:output_type -> snowgauge.Reading
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protocols_snowgauge_snowgauge_proto_init() }
func file_protocols_snowgauge_snowgauge_proto_init() {
	if File_protocols_snowgauge_snowgauge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocols_snowgauge_snowgauge_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*StreamRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocols_snowgauge_snowgauge_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Reading); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protocols_snowgauge_snowgauge_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocols_snowgauge_snowgauge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protocols_snowgauge_snowgauge_proto_goTypes,
		DependencyIndexes: file_protocols_snowgauge_snowgauge_proto_depIdxs,
		MessageInfos:      file_protocols_snowgauge_snowgauge_proto_msgTypes,
	}.Build()
	File_protocols_snowgauge_snowgauge_proto = out.File
	file_protocols_snowgauge_snowgauge_proto_rawDesc = nil
	file_protocols_snowgauge_snowgauge_proto_goTypes = nil
	file_protocols_snowgauge_snowgauge_proto_depIdxs = nil
}
