# Test configuration for Davis emulator with debug logging
# This config connects to a Davis emulator running on localhost:8124

devices:
  - name: "davis-test"
    type: "davis"
    hostname: "localhost"
    port: "8124"
    solar:
      latitude: 45.5152    # Portland, Oregon latitude
      longitude: -122.6784  # Portland, Oregon longitude
      altitude: 50.0        # Elevation in meters

storage:
  # No storage backends configured for testing
  # Readings will be discarded after logging

controllers:
  # No controllers configured for this test
  # Just testing the weather station data flow 