# Comprehensive Weather Station Configuration
# This example demonstrates a full-featured setup with multiple devices,
# storage backends, and controller integrations.

devices:
  - name: "main-weather-station"
    type: "davis"
    hostname: "192.168.1.100"
    port: "22222"
    wind-dir-correction: 15  # Adjust for local magnetic declination
    solar:
      latitude: 45.5152
      longitude: -122.6784
      altitude: 50.0

  - name: "snow-gauge-1"
    type: "snowgauge"
    hostname: "192.168.1.101"
    port: "50051"
    base-snow-distance: 3000  # Distance in mm when no snow present

  - name: "backup-station"
    type: "campbell"
    serial-device: "/dev/ttyUSB0"
    baud: 9600

storage:
  # Primary time-series database
  timescaledb:
    connection-string: "postgresql://weather:password@localhost:5432/weather?sslmode=disable"
  
  # Secondary storage for compatibility
  influxdb:
    scheme: "http"
    host: "localhost"
    port: 8086
    database: "weather"
    username: "admin"
    password: "secret"
    protocol: "http"

  # Real-time streaming for clients
  grpc:
    port: 50051
    listen-addr: "0.0.0.0"
    pull-from-device: "main-weather-station"
    cert: "/etc/ssl/weather.crt"
    key: "/etc/ssl/weather.key"

  # APRS/CWOP reporting
  aprs:
    callsign: "N0CALL"
    passcode: "12345"
    aprs-is-server: "noam.aprs2.net:14580"
    location:
      latitude: 45.5152
      longitude: -122.6784

controllers:
  # Web interface
  - type: "rest"
    rest:
      port: 8080
      listen-addr: "0.0.0.0"
      cert: "/etc/ssl/weather.crt"
      key: "/etc/ssl/weather.key"
      weather-site:
        station-name: "Portland Weather Station"
        pull-from-device: "main-weather-station"
        page-title: "Portland Local Weather"
        snow-enabled: true
        snow-device: "snow-gauge-1"
        about-station-html: |
          <p>Welcome to the Portland Weather Station!</p>
          <p>This station provides real-time weather data including temperature, 
          humidity, wind, rainfall, and snow depth measurements.</p>
          <p>Data is updated every 2.5 seconds and archived for historical analysis.</p>

  # PWS Weather upload
  - type: "pwsweather"
    pwsweather:
      station-id: "KORPORTL123"
      api-key: "your-api-key-here"
      upload-interval: "60"
      pull-from-device: "main-weather-station"
      api-endpoint: "https://pwsupdate.pwsweather.com/api/v1/submitwx"

  # Weather Underground integration
  - type: "weatherunderground"
    weatherunderground:
      station-id: "KORPORTL123"
      api-key: "your-wu-api-key-here"
      upload-interval: "300"
      pull-from-device: "main-weather-station"

  # Aeris Weather forecasting
  - type: "aerisweather"
    aerisweather:
      api-client-id: "your-client-id"
      api-client-secret: "your-client-secret"
      location: "portland,or"
      api-endpoint: "https://api.aerisapi.com" 